# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(341, 341)
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 331, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 301, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAlign_Left = QtWidgets.QPushButton(self.widget)
        self.btnAlign_Left.setCheckable(True)
        self.btnAlign_Left.setAutoRepeat(False)
        self.btnAlign_Left.setAutoExclusive(True)
        self.btnAlign_Left.setAutoDefault(False)
        self.btnAlign_Left.setDefault(False)
        self.btnAlign_Left.setFlat(True)
        self.btnAlign_Left.setObjectName("btnAlign_Left")
        self.horizontalLayout_2.addWidget(self.btnAlign_Left)
        self.btnAlign_Center = QtWidgets.QPushButton(self.widget)
        self.btnAlign_Center.setCheckable(True)
        self.btnAlign_Center.setAutoExclusive(True)
        self.btnAlign_Center.setFlat(True)
        self.btnAlign_Center.setObjectName("btnAlign_Center")
        self.horizontalLayout_2.addWidget(self.btnAlign_Center)
        self.btnAlign_Right = QtWidgets.QPushButton(self.widget)
        self.btnAlign_Right.setCheckable(True)
        self.btnAlign_Right.setAutoExclusive(True)
        self.btnAlign_Right.setFlat(True)
        self.btnAlign_Right.setObjectName("btnAlign_Right")
        self.horizontalLayout_2.addWidget(self.btnAlign_Right)
        self.editInput = QtWidgets.QTextEdit(Widget)
        self.editInput.setGeometry(QtCore.QRect(20, 180, 301, 121))
        self.editInput.setObjectName("editInput")
        self.widget1 = QtWidgets.QWidget(Widget)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget2 = QtWidgets.QWidget(Widget)
        self.widget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget3 = QtWidgets.QWidget(Widget)
        self.widget3.setGeometry(QtCore.QRect(10, 120, 321, 31))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkBox_Readonly = QtWidgets.QCheckBox(self.widget3)
        self.chkBox_Readonly.setObjectName("chkBox_Readonly")
        self.horizontalLayout_3.addWidget(self.chkBox_Readonly)
        self.chkBox_Enabled = QtWidgets.QCheckBox(self.widget3)
        self.chkBox_Enabled.setObjectName("chkBox_Enabled")
        self.horizontalLayout_3.addWidget(self.chkBox_Enabled)
        self.chkBox_ClearButton = QtWidgets.QCheckBox(self.widget3)
        self.chkBox_ClearButton.setObjectName("chkBox_ClearButton")
        self.horizontalLayout_3.addWidget(self.chkBox_ClearButton)
        self.widget4 = QtWidgets.QWidget(Widget)
        self.widget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 331, 61))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget5.setGeometry(QtCore.QRect(10, 20, 301, 25))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAlign_Bold = QtWidgets.QPushButton(self.widget5)
        self.btnAlign_Bold.setCheckable(True)
        self.btnAlign_Bold.setAutoExclusive(False)
        self.btnAlign_Bold.setObjectName("btnAlign_Bold")
        self.horizontalLayout.addWidget(self.btnAlign_Bold)
        self.btnAlign_Italic = QtWidgets.QPushButton(self.widget5)
        self.btnAlign_Italic.setCheckable(True)
        self.btnAlign_Italic.setAutoExclusive(False)
        self.btnAlign_Italic.setObjectName("btnAlign_Italic")
        self.horizontalLayout.addWidget(self.btnAlign_Italic)
        self.btnAlign_Underline = QtWidgets.QPushButton(self.widget5)
        self.btnAlign_Underline.setCheckable(True)
        self.btnAlign_Underline.setAutoExclusive(False)
        self.btnAlign_Underline.setObjectName("btnAlign_Underline")
        self.horizontalLayout.addWidget(self.btnAlign_Underline)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.btnAlign_Left.setText(_translate("Widget", "居左"))
        self.btnAlign_Center.setText(_translate("Widget", "居中"))
        self.btnAlign_Right.setText(_translate("Widget", "居右"))
        self.chkBox_Readonly.setText(_translate("Widget", "Readonly"))
        self.chkBox_Enabled.setText(_translate("Widget", "Enabled"))
        self.chkBox_ClearButton.setText(_translate("Widget", "ClearButtonEnabled"))
        self.btnAlign_Bold.setText(_translate("Widget", "B 粗体"))
        self.btnAlign_Italic.setText(_translate("Widget", " I 斜体"))
        self.btnAlign_Underline.setText(_translate("Widget", "U 下划线"))
